---
- name: Setup Nginx Web Server
  hosts: all
  become: yes

  tasks:
  - name: Update & Upgrade Private Servers
    apt:
      update_cache: yes
      upgrade: yes

  - name: Install Nginx Web Server
    apt:
      name: nginx
      state: latest

  - name: Add Hostname To Display On Server
    tags: print
    shell: echo "<h1>Hello moderator, this is my server and it identifies as $(hostname -f)</h1>" > /var/www/html/index.nginx-debian.html

  - name: Restart Nginx
    tags: restart
    service:
      name: nginx
      state: restarted
      enabled: yes
